/*
 * AdventOS libcrypto — RSA (session 58).
 *
 * RSA-PKCS#1 v1.5 signature scheme over SHA-256 (RFC 8017 §9.2 + §8.2).
 * The most common shape in the wild: every X.509 cert chain you'll see
 * outside of the modern Ed25519/ECDSA crowd uses some variant of this.
 *
 * Scope:
 *
 *   * rsa_verify_pkcs1_sha256 — given (msg, sig, n, e), checks the
 *     signature.  Used by TLS clients verifying server certs and SSH
 *     clients verifying ssh-rsa host keys (signature alg
 *     rsa-sha2-256, RFC 8332).
 *
 *   * rsa_sign_pkcs1_sha256   — given (msg, kp), produces the sig.
 *     Uses the Chinese Remainder Theorem for ~4x speedup over a
 *     straight d-modpow when p / q / dp / dq / qinv are populated.
 *
 *   * rsa_keygen              — generates a fresh (n, e, d) plus the
 *     CRT helpers via Miller-Rabin.  Slow at 2048 bits (tens of seconds
 *     in QEMU), reasonable at 512.  Use precomputed keys for tests.
 *
 * What's deliberately missing:
 *
 *   * RSA-PSS (PKCS#1 v2.1 signing) — more modern, but PKCS#1 v1.5
 *     is what real-world certs and ssh-rsa interop need.
 *   * Encryption (RSAES-OAEP / PKCS#1 v1.5 enc) — separate from
 *     signing and not used by the protocols we ship.
 *   * Constant-time bignum.  Side-channel-vulnerable. Hobby-OS scope.
 *
 * Key sizes:
 *
 *   * Tests use 2048-bit keys (256-byte modulus).
 *   * The keygen path is parameterized on `bits`; 512 is fast enough
 *     for a [t41] roundtrip in well under a second.
 */
#ifndef ADVENTOS_LIBCRYPTO_RSA_H
#define ADVENTOS_LIBCRYPTO_RSA_H

#include "bignum.h"

/* Hard cap on modulus size we accept end-to-end.  Wire formats
 * (PKCS#1, X.509, SSH) all encode the modulus byte length, so this is
 * just our static-buffer ceiling, not an algorithmic limit. */
#define RSA_MAX_BYTES  512                    /* 4096-bit max */

struct rsa_keypair {
    bignum n;          /* modulus */
    bignum e;          /* public exponent (typically 65537) */
    bignum d;          /* private exponent */
    /* CRT precomputed helpers — set iff the keypair was generated by
     * rsa_keygen() or loaded with both primes populated.  When p.n
     * == 0, the signer falls back to plain modpow with d. */
    bignum p;
    bignum q;
    bignum dp;         /* d mod (p - 1) */
    bignum dq;         /* d mod (q - 1) */
    bignum qinv;       /* q^-1 mod p */
};

/* PKCS#1 v1.5 signature with SHA-256.  Writes `sig_len_out` bytes
 * (= byte length of n) into sig.  Returns 0 on success, -1 on
 * structural error (sig buffer too small, etc.). */
int rsa_sign_pkcs1_sha256(uint8_t *sig, int sig_cap, int *sig_len_out,
                          const uint8_t *msg, size_t msg_len,
                          const struct rsa_keypair *kp);

/* PKCS#1 v1.5 verify with SHA-256.  Returns 0 if the signature
 * decodes cleanly and matches sha256(msg); -1 otherwise. */
int rsa_verify_pkcs1_sha256(const uint8_t *msg, size_t msg_len,
                            const uint8_t *sig, size_t sig_len,
                            const bignum *n, const bignum *e);

/* Generate a fresh RSA keypair with the requested modulus size in
 * bits.  Public exponent is fixed at 65537 (the universal default).
 *
 * Cost scales as O(bits^4) — 512-bit keygen takes a fraction of a
 * second in QEMU, 1024 ~5s, 2048 ~30s+.  The selftest defaults to
 * 512 for runtime.
 *
 * Returns 0 on success.  Fails (-1) only on programmer errors
 * (out-of-range bits, etc.) — RNG failure isn't modeled because
 * our rand_bytes never fails. */
int rsa_keygen(struct rsa_keypair *kp, int bits);

#endif
