#include "fbcon.h"
#include "vbe.h"
#include "font8x8.h"
#include "string.h"
#include "kprintf.h"

/* Glyph metrics — the font header pins them but we cache locally
 * so the tight putc loop avoids macro indirection. */
#define GW  FONT_W
#define GH  FONT_H

/* Cursor position in glyph-cells (not pixels). cols/rows are derived
 * once at init. */
static int      g_enabled;
static uint32_t g_cols;
static uint32_t g_rows;
static uint32_t g_cur_col;
static uint32_t g_cur_row;
static uint32_t g_fg = FBC_GREY;
static uint32_t g_bg = FBC_BLACK;

/* Convenience pointer to the FB; cached at init so we don't go through
 * vbe_state() on every pixel write. NULL when disabled. */
static volatile uint8_t *g_fb;
static uint32_t          g_pitch;
static uint32_t          g_bpp;
static uint32_t          g_width;
static uint32_t          g_height;

/* Pack a 24-bit colour into the FB's actual pixel format. We only
 * support the common BGRX layouts QEMU's std-vga emits:
 *   16 bpp = R5 G6 B5 (little-endian)
 *   24 bpp = B G R     (3 bytes per pixel)
 *   32 bpp = B G R X   (4 bytes; X = alpha or padding, ignored) */
static inline uint32_t pack_pixel(uint32_t rgb) {
    if (g_bpp == 16) {
        uint32_t r = (rgb >> 16) & 0xFF;
        uint32_t g = (rgb >>  8) & 0xFF;
        uint32_t b =  rgb        & 0xFF;
        return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
    }
    /* 24 and 32 bpp share the same byte ordering; 32-bpp gets a 0
     * top byte for free since the upper 8 bits of `rgb` are 0. */
    uint32_t r = (rgb >> 16) & 0xFF;
    uint32_t g = (rgb >>  8) & 0xFF;
    uint32_t b =  rgb        & 0xFF;
    return (r << 16) | (g << 8) | b;
}

/* Plot a single pixel. Out-of-range coordinates are silently dropped —
 * the boot path generated by draw_glyph + newline can momentarily
 * stage a write at row=g_rows before scroll_up_one runs (the cursor
 * advances past the bottom row in fbcon_putc, then newline catches it
 * on the very next call). The clamp keeps us from page-faulting on
 * the byte just past the end of the FB. */
static inline void put_pixel(uint32_t x, uint32_t y, uint32_t pix) {
    if (x >= g_width || y >= g_height) return;
    volatile uint8_t *row = g_fb + (uintptr_t)y * g_pitch;
    if (g_bpp == 32) {
        ((volatile uint32_t *)row)[x] = pix;
    } else if (g_bpp == 24) {
        volatile uint8_t *p = row + x * 3;
        p[0] = (uint8_t)(pix);          /* B */
        p[1] = (uint8_t)(pix >> 8);     /* G */
        p[2] = (uint8_t)(pix >> 16);    /* R */
    } else { /* 16 */
        ((volatile uint16_t *)row)[x] = (uint16_t)pix;
    }
}

void fbcon_fill_rect(uint32_t x, uint32_t y,
                     uint32_t w, uint32_t h, uint32_t color) {
    if (!g_enabled) return;
    if (x >= g_width || y >= g_height) return;
    if (x + w > g_width)  w = g_width  - x;
    if (y + h > g_height) h = g_height - y;
    uint32_t pix = pack_pixel(color);
    for (uint32_t yy = 0; yy < h; yy++) {
        for (uint32_t xx = 0; xx < w; xx++) {
            put_pixel(x + xx, y + yy, pix);
        }
    }
}

/* Render one glyph at glyph-cell (col,row). Background is filled
 * solid; foreground bits come from the font table. */
static void draw_glyph(uint32_t col, uint32_t row, char c) {
    uint32_t px = col * GW;
    uint32_t py = row * GH;
    uint32_t fg = pack_pixel(g_fg);
    uint32_t bg = pack_pixel(g_bg);

    const uint8_t *glyph;
    if ((uint8_t)c < FONT_FIRST_CH || (uint8_t)c > FONT_LAST_CH) {
        c = '?';
    }
    glyph = font8x8[(uint8_t)c - FONT_FIRST_CH];

    for (int r = 0; r < GH; r++) {
        uint8_t bits = glyph[r];
        for (int x = 0; x < GW; x++) {
            put_pixel(px + x, py + r, (bits & (1 << x)) ? fg : bg);
        }
    }
}

/* Scroll the entire console up by one glyph row. We do this with a
 * memmove on each FB scanline (8 lines = one text row) followed by
 * blanking the bottom strip. memmove is overkill — the regions don't
 * overlap by row — but it's correct and fast enough for 1024x768. */
static void scroll_up_one(void) {
    uint32_t scanlines = (g_rows - 1) * GH;
    uint32_t row_bytes = g_pitch;

    /* Shift scanlines [GH .. (rows*GH)-1] up by GH lines. */
    for (uint32_t y = 0; y < scanlines; y++) {
        volatile uint8_t *dst = g_fb + (uintptr_t)y       * row_bytes;
        volatile uint8_t *src = g_fb + (uintptr_t)(y+GH)  * row_bytes;
        memcpy((void *)dst, (const void *)src, g_width * (g_bpp / 8));
    }

    /* Blank the freed bottom strip (last GH scanlines). */
    fbcon_fill_rect(0, scanlines, g_width, GH, g_bg);
}

static void newline(void) {
    g_cur_col = 0;
    g_cur_row++;
    if (g_cur_row >= g_rows) {
        scroll_up_one();
        g_cur_row = g_rows - 1;
    }
}

void fbcon_putc(char c) {
    if (!g_enabled) return;

    switch (c) {
        case '\n':
            newline();
            break;
        case '\r':
            g_cur_col = 0;
            break;
        case '\b':
            if (g_cur_col > 0) {
                g_cur_col--;
                draw_glyph(g_cur_col, g_cur_row, ' ');
            }
            break;
        case '\t':
            g_cur_col = (g_cur_col + 4) & ~3u;
            if (g_cur_col >= g_cols) newline();
            break;
        default:
            if ((uint8_t)c < 0x20) break;     /* drop other controls */
            draw_glyph(g_cur_col, g_cur_row, c);
            g_cur_col++;
            if (g_cur_col >= g_cols) newline();
            break;
    }
}

void fbcon_write(const char *s) {
    while (*s) fbcon_putc(*s++);
}

void fbcon_clear(void) {
    if (!g_enabled) return;
    fbcon_fill_rect(0, 0, g_width, g_height, g_bg);
    g_cur_col = g_cur_row = 0;
}

void fbcon_set_color(uint32_t fg, uint32_t bg) {
    g_fg = fg;
    g_bg = bg;
}

void fbcon_init(void) {
    if (g_enabled) return;
    const struct vbe_state *v = vbe_state();
    if (!v->enabled) {
        kprintf("fbcon: vbe disabled — fbcon stays off\n");
        return;
    }

    g_fb     = v->fb;
    g_pitch  = v->pitch;
    g_bpp    = v->bpp;
    g_width  = v->width;
    g_height = v->height;
    g_cols   = g_width  / GW;
    g_rows   = g_height / GH;
    g_cur_col = g_cur_row = 0;
    g_enabled = 1;

    /* Paint a clean canvas so the first kprintf doesn't land on top
     * of the BIOS splash logo or boot-time noise. */
    fbcon_clear();
    kprintf("fbcon: %ux%u glyph cells (%u-bpp)\n",
            (unsigned)g_cols, (unsigned)g_rows, (unsigned)g_bpp);
}

int fbcon_enabled(void) { return g_enabled; }
