/*
 * httpsd — HTTPS server backed by AdventOS minimal TLS 1.3.
 *
 * Listens on TCP port 4433 (the conventional HTTPS-on-non-443 port,
 * useful since our HTTP server already uses 80). On each accept,
 * runs a TLS handshake using a hardcoded PSK, reads the HTTP
 * request, and responds with a static page.
 *
 * Both sides use the same PSK identity / key — the client demo
 * (httpsget) is configured matching. In a real deployment the PSK
 * would be provisioned out-of-band; this is a demo so it's compiled
 * in. Under the AdventOS demo network (single host, no eavesdroppers
 * on the QEMU SLIRP NAT), the PSK is fine for showing TLS works.
 */
#include "libuser.h"
#include "../libcrypto/crypto.h"
#include "../libcrypto/tls.h"

#define HTTPS_PORT  4433

/* The shared PSK. 32 bytes of high-entropy material — in a real
 * system, generated by a HSM or DH-derived. */
static const unsigned char DEMO_PSK[32] = {
    0xA5, 0x3F, 0x91, 0x77, 0xB2, 0xCE, 0x40, 0x06,
    0x88, 0xDD, 0x21, 0x55, 0x9C, 0x4E, 0xFA, 0x33,
    0x71, 0x82, 0x49, 0xBE, 0x0F, 0x6A, 0x1D, 0x55,
    0xC8, 0x37, 0x12, 0xE6, 0xAB, 0x90, 0x44, 0x68,
};
static const char DEMO_PSK_ID[] = "adventos-demo-psk-v1";

/* Static reply. Mirrors httpd's structure. */
static const char REPLY[] =
    "HTTP/1.0 200 OK\r\n"
    "Content-Type: text/plain\r\n"
    "Connection: close\r\n"
    "\r\n"
    "Hello from a TLS 1.3 + HTTPS server in AdventOS!\n"
    "\n"
    "The bytes you received were:\n"
    "  - Encrypted with AES-128-GCM\n"
    "  - Authenticated with HMAC-SHA-256 (Finished + GCM tag)\n"
    "  - Keyed via X25519 ECDHE + a pre-shared key\n"
    "  - Served by user/httpsd.c, ring 3, 1024 lines of crypto\n"
    "\n"
    "Magic header: ADLC. Cipher suite: TLS_AES_128_GCM_SHA256.\n";

static void serve_one(int conn) {
    struct tls_conn t;
    int hs = tls_server_handshake(&t, conn,
                                  DEMO_PSK, sizeof(DEMO_PSK),
                                  DEMO_PSK_ID);
    if (hs != 0) {
        printf("httpsd: handshake failed (rc=%d)\n", hs);
        sys_close(conn);
        return;
    }
    puts("httpsd: TLS handshake OK\n");

    /* Read the request (just to drain it; we don't parse). */
    char req[1024];
    int n = tls_recv(&t, req, sizeof(req) - 1);
    if (n > 0) {
        req[n] = 0;
        /* Print the request line, sans body — diagnostic. */
        for (int i = 0; i < n && i < 128 && req[i] != '\r'; i++) putchar(req[i]);
        putchar('\n');
    }

    /* Send the reply, broken into one record. */
    int sent = tls_send(&t, REPLY, sizeof(REPLY) - 1);
    printf("httpsd: sent %d encrypted bytes\n", sent);
    sys_close(conn);
}

int main(void) {
    int srv = sys_socket();
    if (srv < 0) { puts("httpsd: socket failed\n"); return 1; }
    if (sys_bind(srv, HTTPS_PORT) < 0) {
        puts("httpsd: bind failed\n");
        sys_close(srv);
        return 1;
    }
    if (sys_listen(srv, 4) < 0) {
        puts("httpsd: listen failed\n");
        sys_close(srv);
        return 1;
    }
    printf("httpsd: listening on TLS port %d (PSK id=\"%s\")\n",
           HTTPS_PORT, DEMO_PSK_ID);

    /* Accept loop. fork-per-connection. */
    for (;;) {
        int conn = sys_accept(srv);
        if (conn < 0) { sys_sleep_ms(100); continue; }

        int pid = sys_fork();
        if (pid == 0) {
            sys_close(srv);
            serve_one(conn);
            sys_exit(0);
        }
        sys_close(conn);
        /* Reap zombies non-blockingly. */
        int code;
        while (sys_wait_nb(&code) > 0) {}
    }
    return 0;
}
